name: Karbala Stream Direct
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Run Stream
        run: |
          ffmpeg -re -i "https://stream.alkafeel.net/live/alkafeel/playlist.m3u8" \
          -vf "drawtext=text='عـيـن كـربـلاء':x=w-tw:y=0:fontsize=70:fontcolor='#FFD700':box=1:boxcolor=black@1:boxborderw=35, \
          drawtext=text='اللهم ارزقنا زيارة الحسين في الدنيا وشفاعته في الآخرة .. قناة عين كربلاء ترحب بكم':x=-tw+mod(t*80\,w+tw):y=h-th-5:fontsize=45:fontcolor=white:box=1:boxcolor=black@0.6" \
          -c:v libx264 -preset ultrafast -tune zerolatency -b:v 1500k -maxrate 1500k -bufsize 3000k -c:a aac -b:a 128k -f flv "rtmp://a.rtmp.youtube.com/live2/5sm9-j2wv-s92e-z6uf-30x6"
