name: Karbala Stream Direct
on:
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg wget
      - name: Run Stream
        run: |
          wget -q https://github.com/google/fonts/raw/main/ofl/amiri/Amiri-Bold.ttf -O font.ttf
          ffmpeg -re -i "https://stream.alkafeel.net/live/alkafeel/playlist.m3u8" \
          -vf "drawtext=fontfile=font.ttf:text='عين كربلاء':x=w-tw-5:y=5:fontsize=70:fontcolor='#FFD700':box=1:boxcolor=black@0.8" \
          -c:v libx264 -preset superfast -b:v 1500k -c:a aac -f flv "rtmp://a.rtmp.youtube.com/live2/5sm9-j2wv-s92e-z6uf-30x6"
