name: Karbala Stream 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # يعيد تشغيل نفسه كل 6 ساعات لضمان الاستمرار

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Run Docker
        run: |
          docker build -t stream-image .
          docker run stream-image
